name: unit-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    env:
      GOFLAGS: "-mod=vendor"
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up gotestfmt
        uses: gotesttools/gotestfmt-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Environment info
        run: |
          echo "Go Version:"
          go version
          echo "\nGo env:"
          go env
          echo "\nPATH:"
          echo $PATH

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v . -json 2>&1 | gotestfmt -hide empty-packages
        id: test
        continue-on-error: true

      - name: Race Test
        run: go test -v . -race -json 2>&1 | gotestfmt -hide empty-packages
        id: race
        continue-on-error: true

      - name: Tests Successful
        if: steps.test.outcome == 'failure' || steps.race.outcome == 'failure'
        shell: bash
        run: exit 1
