name: unit-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    env:
      GOFLAGS: "-mod=vendor"
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:

      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up gotestfmt
        uses: gotesttools/gotestfmt-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: debug
        run: |
          go version
          go env
          echo $PATH

      - name: Build
        run: go build -v .

      - name: Race Test
        run: go test -v . -race -json 2>&1 | gotestfmt -hide empty-packages

      - name: Test
        run: go test -v . -count 5 -json 2>&1 | gotestfmt -hide empty-packages
